// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package bear

import (
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_Bear            protoreflect.MessageDescriptor
	fd_Bear_role       protoreflect.FieldDescriptor
	fd_Bear_background protoreflect.FieldDescriptor
	fd_Bear_clothes    protoreflect.FieldDescriptor
	fd_Bear_weapon     protoreflect.FieldDescriptor
	fd_Bear_creator    protoreflect.FieldDescriptor
	fd_Bear_id         protoreflect.FieldDescriptor
)

func init() {
	file_bear_bear_bear_proto_init()
	md_Bear = File_bear_bear_bear_proto.Messages().ByName("Bear")
	fd_Bear_role = md_Bear.Fields().ByName("role")
	fd_Bear_background = md_Bear.Fields().ByName("background")
	fd_Bear_clothes = md_Bear.Fields().ByName("clothes")
	fd_Bear_weapon = md_Bear.Fields().ByName("weapon")
	fd_Bear_creator = md_Bear.Fields().ByName("creator")
	fd_Bear_id = md_Bear.Fields().ByName("id")
}

var _ protoreflect.Message = (*fastReflection_Bear)(nil)

type fastReflection_Bear Bear

func (x *Bear) ProtoReflect() protoreflect.Message {
	return (*fastReflection_Bear)(x)
}

func (x *Bear) slowProtoReflect() protoreflect.Message {
	mi := &file_bear_bear_bear_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_Bear_messageType fastReflection_Bear_messageType
var _ protoreflect.MessageType = fastReflection_Bear_messageType{}

type fastReflection_Bear_messageType struct{}

func (x fastReflection_Bear_messageType) Zero() protoreflect.Message {
	return (*fastReflection_Bear)(nil)
}
func (x fastReflection_Bear_messageType) New() protoreflect.Message {
	return new(fastReflection_Bear)
}
func (x fastReflection_Bear_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_Bear
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_Bear) Descriptor() protoreflect.MessageDescriptor {
	return md_Bear
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_Bear) Type() protoreflect.MessageType {
	return _fastReflection_Bear_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_Bear) New() protoreflect.Message {
	return new(fastReflection_Bear)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_Bear) Interface() protoreflect.ProtoMessage {
	return (*Bear)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_Bear) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Role != "" {
		value := protoreflect.ValueOfString(x.Role)
		if !f(fd_Bear_role, value) {
			return
		}
	}
	if x.Background != "" {
		value := protoreflect.ValueOfString(x.Background)
		if !f(fd_Bear_background, value) {
			return
		}
	}
	if x.Clothes != "" {
		value := protoreflect.ValueOfString(x.Clothes)
		if !f(fd_Bear_clothes, value) {
			return
		}
	}
	if x.Weapon != "" {
		value := protoreflect.ValueOfString(x.Weapon)
		if !f(fd_Bear_weapon, value) {
			return
		}
	}
	if x.Creator != "" {
		value := protoreflect.ValueOfString(x.Creator)
		if !f(fd_Bear_creator, value) {
			return
		}
	}
	if x.Id != uint64(0) {
		value := protoreflect.ValueOfUint64(x.Id)
		if !f(fd_Bear_id, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_Bear) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "bear.bear.Bear.role":
		return x.Role != ""
	case "bear.bear.Bear.background":
		return x.Background != ""
	case "bear.bear.Bear.clothes":
		return x.Clothes != ""
	case "bear.bear.Bear.weapon":
		return x.Weapon != ""
	case "bear.bear.Bear.creator":
		return x.Creator != ""
	case "bear.bear.Bear.id":
		return x.Id != uint64(0)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: bear.bear.Bear"))
		}
		panic(fmt.Errorf("message bear.bear.Bear does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Bear) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "bear.bear.Bear.role":
		x.Role = ""
	case "bear.bear.Bear.background":
		x.Background = ""
	case "bear.bear.Bear.clothes":
		x.Clothes = ""
	case "bear.bear.Bear.weapon":
		x.Weapon = ""
	case "bear.bear.Bear.creator":
		x.Creator = ""
	case "bear.bear.Bear.id":
		x.Id = uint64(0)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: bear.bear.Bear"))
		}
		panic(fmt.Errorf("message bear.bear.Bear does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_Bear) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "bear.bear.Bear.role":
		value := x.Role
		return protoreflect.ValueOfString(value)
	case "bear.bear.Bear.background":
		value := x.Background
		return protoreflect.ValueOfString(value)
	case "bear.bear.Bear.clothes":
		value := x.Clothes
		return protoreflect.ValueOfString(value)
	case "bear.bear.Bear.weapon":
		value := x.Weapon
		return protoreflect.ValueOfString(value)
	case "bear.bear.Bear.creator":
		value := x.Creator
		return protoreflect.ValueOfString(value)
	case "bear.bear.Bear.id":
		value := x.Id
		return protoreflect.ValueOfUint64(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: bear.bear.Bear"))
		}
		panic(fmt.Errorf("message bear.bear.Bear does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Bear) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "bear.bear.Bear.role":
		x.Role = value.Interface().(string)
	case "bear.bear.Bear.background":
		x.Background = value.Interface().(string)
	case "bear.bear.Bear.clothes":
		x.Clothes = value.Interface().(string)
	case "bear.bear.Bear.weapon":
		x.Weapon = value.Interface().(string)
	case "bear.bear.Bear.creator":
		x.Creator = value.Interface().(string)
	case "bear.bear.Bear.id":
		x.Id = value.Uint()
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: bear.bear.Bear"))
		}
		panic(fmt.Errorf("message bear.bear.Bear does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Bear) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "bear.bear.Bear.role":
		panic(fmt.Errorf("field role of message bear.bear.Bear is not mutable"))
	case "bear.bear.Bear.background":
		panic(fmt.Errorf("field background of message bear.bear.Bear is not mutable"))
	case "bear.bear.Bear.clothes":
		panic(fmt.Errorf("field clothes of message bear.bear.Bear is not mutable"))
	case "bear.bear.Bear.weapon":
		panic(fmt.Errorf("field weapon of message bear.bear.Bear is not mutable"))
	case "bear.bear.Bear.creator":
		panic(fmt.Errorf("field creator of message bear.bear.Bear is not mutable"))
	case "bear.bear.Bear.id":
		panic(fmt.Errorf("field id of message bear.bear.Bear is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: bear.bear.Bear"))
		}
		panic(fmt.Errorf("message bear.bear.Bear does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_Bear) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "bear.bear.Bear.role":
		return protoreflect.ValueOfString("")
	case "bear.bear.Bear.background":
		return protoreflect.ValueOfString("")
	case "bear.bear.Bear.clothes":
		return protoreflect.ValueOfString("")
	case "bear.bear.Bear.weapon":
		return protoreflect.ValueOfString("")
	case "bear.bear.Bear.creator":
		return protoreflect.ValueOfString("")
	case "bear.bear.Bear.id":
		return protoreflect.ValueOfUint64(uint64(0))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: bear.bear.Bear"))
		}
		panic(fmt.Errorf("message bear.bear.Bear does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_Bear) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in bear.bear.Bear", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_Bear) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Bear) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_Bear) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_Bear) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*Bear)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		l = len(x.Role)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Background)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Clothes)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Weapon)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Creator)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.Id != 0 {
			n += 1 + runtime.Sov(uint64(x.Id))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*Bear)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if x.Id != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Id))
			i--
			dAtA[i] = 0x30
		}
		if len(x.Creator) > 0 {
			i -= len(x.Creator)
			copy(dAtA[i:], x.Creator)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Creator)))
			i--
			dAtA[i] = 0x2a
		}
		if len(x.Weapon) > 0 {
			i -= len(x.Weapon)
			copy(dAtA[i:], x.Weapon)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Weapon)))
			i--
			dAtA[i] = 0x22
		}
		if len(x.Clothes) > 0 {
			i -= len(x.Clothes)
			copy(dAtA[i:], x.Clothes)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Clothes)))
			i--
			dAtA[i] = 0x1a
		}
		if len(x.Background) > 0 {
			i -= len(x.Background)
			copy(dAtA[i:], x.Background)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Background)))
			i--
			dAtA[i] = 0x12
		}
		if len(x.Role) > 0 {
			i -= len(x.Role)
			copy(dAtA[i:], x.Role)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Role)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*Bear)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Bear: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Bear: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Role", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Role = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Background", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Background = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Clothes", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Clothes = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Weapon", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Weapon = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 5:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Creator = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 6:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
				}
				x.Id = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Id |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: bear/bear/bear.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bear struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Role       string `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Background string `protobuf:"bytes,2,opt,name=background,proto3" json:"background,omitempty"`
	Clothes    string `protobuf:"bytes,3,opt,name=clothes,proto3" json:"clothes,omitempty"`
	Weapon     string `protobuf:"bytes,4,opt,name=weapon,proto3" json:"weapon,omitempty"`
	Creator    string `protobuf:"bytes,5,opt,name=creator,proto3" json:"creator,omitempty"`
	Id         uint64 `protobuf:"varint,6,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Bear) Reset() {
	*x = Bear{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bear_bear_bear_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bear) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bear) ProtoMessage() {}

// Deprecated: Use Bear.ProtoReflect.Descriptor instead.
func (*Bear) Descriptor() ([]byte, []int) {
	return file_bear_bear_bear_proto_rawDescGZIP(), []int{0}
}

func (x *Bear) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Bear) GetBackground() string {
	if x != nil {
		return x.Background
	}
	return ""
}

func (x *Bear) GetClothes() string {
	if x != nil {
		return x.Clothes
	}
	return ""
}

func (x *Bear) GetWeapon() string {
	if x != nil {
		return x.Weapon
	}
	return ""
}

func (x *Bear) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *Bear) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_bear_bear_bear_proto protoreflect.FileDescriptor

var file_bear_bear_bear_proto_rawDesc = []byte{
	0x0a, 0x14, 0x62, 0x65, 0x61, 0x72, 0x2f, 0x62, 0x65, 0x61, 0x72, 0x2f, 0x62, 0x65, 0x61, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x62, 0x65, 0x61, 0x72, 0x2e, 0x62, 0x65, 0x61,
	0x72, 0x22, 0x96, 0x01, 0x0a, 0x04, 0x42, 0x65, 0x61, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f,
	0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x1e,
	0x0a, 0x0a, 0x62, 0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x62, 0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6c, 0x6f, 0x74, 0x68, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x6c, 0x6f, 0x74, 0x68, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x65, 0x61, 0x70,
	0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x77, 0x65, 0x61, 0x70, 0x6f, 0x6e,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x42, 0x7b, 0x0a, 0x0d, 0x63, 0x6f,
	0x6d, 0x2e, 0x62, 0x65, 0x61, 0x72, 0x2e, 0x62, 0x65, 0x61, 0x72, 0x42, 0x09, 0x42, 0x65, 0x61,
	0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x1a, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73,
	0x73, 0x64, 0x6b, 0x2e, 0x69, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x62, 0x65, 0x61, 0x72, 0x2f,
	0x62, 0x65, 0x61, 0x72, 0xa2, 0x02, 0x03, 0x42, 0x42, 0x58, 0xaa, 0x02, 0x09, 0x42, 0x65, 0x61,
	0x72, 0x2e, 0x42, 0x65, 0x61, 0x72, 0xca, 0x02, 0x09, 0x42, 0x65, 0x61, 0x72, 0x5c, 0x42, 0x65,
	0x61, 0x72, 0xe2, 0x02, 0x15, 0x42, 0x65, 0x61, 0x72, 0x5c, 0x42, 0x65, 0x61, 0x72, 0x5c, 0x47,
	0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0a, 0x42, 0x65, 0x61,
	0x72, 0x3a, 0x3a, 0x42, 0x65, 0x61, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bear_bear_bear_proto_rawDescOnce sync.Once
	file_bear_bear_bear_proto_rawDescData = file_bear_bear_bear_proto_rawDesc
)

func file_bear_bear_bear_proto_rawDescGZIP() []byte {
	file_bear_bear_bear_proto_rawDescOnce.Do(func() {
		file_bear_bear_bear_proto_rawDescData = protoimpl.X.CompressGZIP(file_bear_bear_bear_proto_rawDescData)
	})
	return file_bear_bear_bear_proto_rawDescData
}

var file_bear_bear_bear_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_bear_bear_bear_proto_goTypes = []interface{}{
	(*Bear)(nil), // 0: bear.bear.Bear
}
var file_bear_bear_bear_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bear_bear_bear_proto_init() }
func file_bear_bear_bear_proto_init() {
	if File_bear_bear_bear_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bear_bear_bear_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bear); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bear_bear_bear_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bear_bear_bear_proto_goTypes,
		DependencyIndexes: file_bear_bear_bear_proto_depIdxs,
		MessageInfos:      file_bear_bear_bear_proto_msgTypes,
	}.Build()
	File_bear_bear_bear_proto = out.File
	file_bear_bear_bear_proto_rawDesc = nil
	file_bear_bear_bear_proto_goTypes = nil
	file_bear_bear_bear_proto_depIdxs = nil
}
